export const GET_CURRENT_COURSE_SUCCESS = "GET_CURRENT_COURSE_SUCCESS";
export const GET_CURRENT_COURSE_FAILED = "GET_CURRENT_COURSE_FAILED";
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";

export const TRACK_SECTION = "TRACK_SECTION";
export const TRACK_SECTION_SUCCESS = "TRACK_SECTION_SUCCESS";
export const TRACK_SECTION_FAILED = "TRACK_SECTION_FAILED";

export const SET_NOTIFICATION_TOKEN = "SET_NOTIFICATION_TOKEN";
