export const GET_CURRENT_COURSE_SUCCESS = "GET_CURRENT_COURSE_SUCCESS";
export const GET_CURRENT_COURSE_FAILED = "GET_CURRENT_COURSE_FAILED";
export const GET_CURRENT_COURSE = "GET_CURRENT_COURSE";

export const TRACK_SECTION = "TRACK_SECTION";
export const TRACK_SECTION_SUCCESS = "TRACK_SECTION_SUCCESS";
export const TRACK_SECTION_FAILED = "TRACK_SECTION_FAILED";

export const UNTRACK_SECTION = "UNTRACK_SECTION";
export const UNTRACK_SECTION_SUCCESS = "UNTRACK_SECTION_SUCCESS";
export const UNTRACK_SECTION_FAILED = "UNTRACK_SECTION_FAILED";

export const SYNC_SECTIONS = "SYNC_SECTIONS";
export const SYNC_SECTIONS_SUCCESS = "SYNC_SECTIONS_SUCCESS";
export const SYNC_SECTIONS_FAILED = "SYNC_SECTIONS_FAILED";

export const SET_NOTIFICATION_TOKEN = "SET_NOTIFICATION_TOKEN";
